### ISSUE TITLE
Community post like polls can be created?

### ISSUE THREAD

**Issue by bsde1234** [Benjamin-Loison/YouTube-operational-API#102]
Can I create community posts like polls with this project? Thanks.

**Comment by Benjamin-Loison** [comment]
Hello, no, my YouTube operational API doesn't allow you to create community posts.

However you can proceed as follows to create as will community posts that are text polls:

Go on your YouTube channel `COMMUNITY` tab: https://www.youtube.com/channel/YOUR_CHANNEL_ID/community

Write a community post that is a text poll but don't click on `Post`.

Open the `Network` tab of your web-browser by using `Ctrl` + `Shift` + `E` (on Firefox) and filter XHR requests.
Now click on `Post`.

You should see a request to `create_post`, copy it as cURL (by right-clicking).
Change at your will at the end `YOUR_QUESTION`, `YOUR_OPTION_0`, `YOUR_OPTION_1`, ... and `YOUR_OPTION_N` in:

```
"commentText":"YOUR_QUESTION","pollAttachment":{"choices":["YOUR_OPTION_0","YOUR_OPTION_1", ..., "YOUR_OPTION_N"]}
```

Execute the modified cURL request in a terminal and that's it!

Note that I don't for how long this cURL will still works.

**Comment by bsde1234** [comment]
Can't find `create_post`. Where is it?

![Screenshot_2022-12-17_23-50-08](https://user-images.githubusercontent.com/35421561/208255975-1e5e5414-3dcd-4c76-a5a9-141bfc237d14.png)

**Comment by Benjamin-Loison** [comment]
> Can't find `create_post`. Where is it?
> 
> ![Screenshot_2022-12-17_23-50-08](https://user-images.githubusercontent.com/35421561/208255975-1e5e5414-3dcd-4c76-a5a9-141bfc237d14.png)

Is your screenshot taken after having clicked on `Post`, as I mentioned?
> Open the `Network` tab of your web-browser by using `Ctrl` + `Shift` + `E` (on Firefox) and filter XHR requests.
> Now click on `Post`.

**Comment by bsde1234** [comment]
Thanks for the quick response, I was following your first post thats now edited. I will check it.

**Comment by bsde1234** [comment]
```
exec("curl 'https://www.youtube.com/youtubei/v1/backstage/create_post?key=AIzaSyAO_FJ2SSTEHLGCilw_Y9_11qcW8&prettyPrint=false' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://www.youtube.com/@KeralaPSCLive/community' -H 'Content-Type: application/json' -H 'X-Goog-Visitor-Id: Cgt2XzkxxxxPZU8zayjwlPicBg%3D%3D' -H 'X-Youtube-Bootstrap-Logged-In: true' -H 'X-Youtube-Client-Name: 1' -H 'X-Youtube-Client-Version: 2.20221215.04.01' -H 'Authorization: SAPISIDHASH 1671302051_30a8a4efxxxxf698d8f4e4543d9c69f94f' -H 'X-Goog-AuthUser: 0' -H 'X-Origin: https://www.youtube.com' -H 'X-Goog-PageId: 1154607931xxxx4037' -H 'Origin: https://www.youtube.com' -H 'Alt-Used: www.youtube.com' -H 'Connection: keep-alive' -H 'Cookie: VISITOR_INFO1_LIVE=v_96qLOeO3k; PREF=f6=40000000&tz=Asia.Kolkata&f7=100; SID=RghXT5Tv0fMmxxxxxx7p6uzfS6T2heZDbh5QFigHSv_RMK_FXeD6wGZvFsw.; __Secure-1PSID=RghXT5Tv0fMmrsQ9iA2Mjt2F0UXtE7pxxxxeZDbh5QFBS1yUH2xlOHizPV0p5tjvA.; __Secure-3PSID=RghXT5Tv0fMmrsQ9iA2Mjt2F0UXxxxxeZDbh5QF_bKC-jghFjuoLHDxwYEWKg.; HSID=A65exxxdEL1j1fC2; SSID=AY-sR0sxxxxC3B; APISID=8mwDJ6uWJEvfaxxxZosE0OHdZF3VSN8_; SAPISID=iRCyRlJqEUMlfF9b/A8JCZOTnwJMmWRXOb; __Secure-1PAPISID=iRCyRlJqEUxxxb/A8JCZOTnwJMmWRXOb; __Secure-3PAPISID=iRCyRlJqEUMlfF9xxxCZOTnwJMmWRXOb; LOGIN_INFO=AFmmF2swRgIhxxxxxxxxnLlQBabssxjW98UAo56HqPe0E2krQol4yZz8lAiEAv6Y96xb1cszzxlF9rSFZI5DUyyMJKSGMUd2byFYxnoY:QUQ3MjNmeWk2dDQ1V3dxSFVOQXlIR0JyUnlCSWRkdTJmcFRETjBOaXFmTEZXUm9RcUhmSVRsVnM3TU1rX3VFNjlNa3p4dmpuanpKY0dZSxxxxxaHhqU0N1SW1qOW1kWVpXUlZ1ZlU4d3J4bmF6aG9JbUJNQ054NGl0UVhmeUJJVXJOR3NLTFI3bjZyTXJYb2VSd3RZLXxxxxx6Z2dfbmhxaHpyTGFyRmdQeWdqOFp1S1E4LUtBUTQzcGY5OS12X1NTNjFvc1hJSnBpZUNic3pidmhPeC1Pem5ZTXJuZw==; SIDCC=AIKkIs3fIx0prlvf91YlJ-KzEdVWjmro_Sa26alGd9_0pInVsUn2F15WvY-hjdJIDw5hmcQAymk; __Secure-1PSIDCC=AIKkIs1LgLO_F7XUKwIgdVAC0KeIt6v-b-u24Cnj0W855GvnBhcE13ay8dxnyMd1xxxxOJh6o; __Secure-3PSIDCC=AIKkIs01s6Cz68n_KEj98MtgxxxxxddatyzYVUhIUWVjgKHs5li_hNxjyDe7RdJ2JPj2s; YSC=fGwWDtGAs4o' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: same-origin' -H 'Sec-Fetch-Site: same-origin' -H 'TE: trailers' --data-raw $'{\"context\":{\"client\":{\"hl\":\"en\",\"gl\":\"IN\",\"remoteHost\":\"223.227.58.168\",\"deviceMake\":\"\",\"deviceModel\":\"\",\"visitorData\":\"Cgt2Xzk2cUxPZU8zayjwlPicBg%3D%3D\",\"userAgent\":\"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0,gzip(gfe)\",\"clientName\":\"WEB\",\"clientVersion\":\"2.20221215.04.01\",\"osName\":\"X11\",\"osVersion\":\"\",\"originalUrl\":\"https://www.youtube.com/\",\"platform\":\"DESKTOP\",\"clientFormFactor\":\"UNKNOWN_FORM_FACTOR\",\"configInfo\":{\"appInstallData\":\"CPCU-JwGEKLsrgUQuIuuBRDX5K4FEILdrgUQixxxxx4SEIfdrgUQuNSuBRDa6a4FEOLUrgUQsoj-EhDM364FEP7krgUQvNquBRDk3a4FEPyc_hIQycmuBRCR-PwSENi-rQU%3D\"},\"userInterfaceTheme\":\"USER_INTERFACE_THEME_DARK\",\"timeZone\":\"Asia/Kolkata\",\"browserName\":\"Firefox\",\"browserVersion\":\"102.0\",\"acceptHeader\":\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8\",\"deviceExperimentId\":\"ChxOekUzT0RFNE5qxxxxxkyTlRNNE1UZ3dOdz09EPCU-JwGGPCU-JwG\",\"screenWidthPoints\":524,\"screenHeightPoints\":621,\"screenPixelDensity\":1,\"screenDensityFloat\":1,\"utcOffsetMinutes\":330,\"mainAppWebInfo\":{\"graftUrl\":\"https://www.youtube.com/@KeralaPSCLive/community\",\"webDisplayMode\":\"WEB_DISPLAY_MODE_BROWSER\",\"isWebNativeShareAvailable\":false}},\"user\":{\"lockedSafetyMode\":false},\"request\":{\"useSsl\":true,\"internalExperimentFlags\":[],\"consistencyTokenJars\":[]},\"clickTracking\":{\"clickTrackingParams\":\"CDAQ8FsiEwj_xo6fpIH8AhUQVY8KHdQ8CS4=\"},\"adSignalsInfo\":{\"params\":[{\"key\":\"dt\",\"value\":\"1671301744995\"},{\"key\":\"flash\",\"value\":\"0\"},{\"key\":\"frm\",\"value\":\"0\"},{\"key\":\"u_tz\",\"value\":\"330\"},{\"key\":\"u_his\",\"value\":\"4\"},{\"key\":\"u_h\",\"value\":\"768\"},{\"key\":\"u_w\",\"value\":\"1024\"},{\"key\":\"u_ah\",\"value\":\"735\"},{\"key\":\"u_aw\",\"value\":\"1024\"},{\"key\":\"u_cd\",\"value\":\"24\"},{\"key\":\"bc\",\"value\":\"31\"},{\"key\":\"bih\",\"value\":\"621\"},{\"key\":\"biw\",\"value\":\"524\"},{\"key\":\"brdim\",\"value\":\"0,33,0,33,10x4,33,1024,76,5x4,621\"},{\"key\":\"vis\",\"value\":\"1\"},{\"key\":\"wgl\",\"value\":\"true\"},{\"key\":\"ca_type\",\"value\":\"image\"}]}},\"createBackstagePostParams\":\"ChhVQ0NwU1E3dVpCMU05LS0xRFA5ZWNqZ0EQATICGAdAAg%3D%3D\",\"commentText\":\"കേരള ഫോറസ്റ്റ് റിസർച്ച് ഇൻസ്റ്റിറ്റ്യൂട്ട് ആസ്ഥാനം?\",\"pollAttachment\":{\"choices\":[\"കോട്ടയം\", \"തിരുവനന്തപുരം\", \"പീച്ചി\"]}}'");
```

I get output like 
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2482  100   176  100  2306    550   7206 --:--:-- --:--:-- --:--:--  7756

```
But poll not posted.

**Comment by Benjamin-Loison** [comment]
@bsde1234 I hide your comment, as I am busy and you've posted similar to your credentials. I have paste your message on my side and we'll reach out to try to help you accordingly.

**Comment by bsde1234** [comment]
I havve replaced some with xxxx

**Comment by bsde1234** [comment]
As you said, when running curl from terminal, poll gets posted. Where is my error in php file?

**Comment by Benjamin-Loison** [comment]
> As you said, when running curl from terminal, poll gets posted. Where is my error in php file?

In Python (instead of *php*) you mean I guess.

With this definition of `exec`:

```py
import subprocess

def exec(cmd):
    subprocess.check_output(cmd, shell=True)
```

When providing to `exec` a `cmd` that is the cURL request that I copied from my Firefox web-brower (108.0.1 (64-bit)) and just replace `"` to `\"` and execute the Python script the text poll is correctly published.

If it still doesn't work on your end, you can remove `-H 'Accept-Encoding: gzip, deflate, br'` from the cURL request and modify `exec` to:

```py
def exec(cmd):
    return subprocess.check_output(cmd, shell=True).decode()
```

in order to have a text response from YouTube servers to your request.

**Comment by bsde1234** [comment]
I am using php here.

```
exec("curl 'https://www.youtube.com/youtubei/v1/backstage/c.........", $output, $return_var);
     
            print_r($output);
            $result_array=explode(' ',$output);
                   echo "Output: ".$result_array."<br>";
                   echo "Exit status: ".$return_var."<br>";
     
```

returns
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2482  100   176  100  2306    407   5337 --:--:-- --:--:-- --:--:--  5745
Array
(
    [0] => jĲ��5�T7~]���vW��X�&��
                                 ÆqZ&�6%�L���ȿ
    [1] => �V�����Q@7)gL08�TA�#N���8��2��׏�LG�0����|�Nz�}{�7�x�z[w����;
                                                                       X-�������Ј���".�8`��\�I���v�3H�C��ꉓ�r�_�
)
PHP Warning:  explode() expects parameter 2 to be string, array given in /home/justinechacko/web/tgquizz/yt-poll.php on line 7
Output: <br>Exit status: 0<br>
```

**Comment by Benjamin-Loison** [comment]
Note that doing `$result_array=explode(' ',$output);` doesn't make sense as `explode` is only defined for `string`s as far as I know and `$output` is an array here according to [exec documentation](https://www.php.net/manual/en/function.exec.php).

If you want to avoid progression output (cf below) you can use `curl -s ...` instead of `curl ...`:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2482  100   176  100  2306    407   5337 --:--:-- --:--:-- --:--:--  5745
```

I confirm one more time that doing:
```php
<?php

    $cmd = "curl 'https://www.youtube.com/youtubei/v1/backstage/c...";
    exec($cmd, $output, $return_var);
    print_r($output);
    echo "Exit status: ".$return_var."<br>";

?>
```

publishes correctly the poll (using PHP 8.1.2-1ubuntu2.9 (cli)).

Note that removing `-H 'Accept-Encoding: gzip, deflate, br'` from the cURL request makes the output readable instead of having:
```
Array
(
    [0] => jĲ��5�T7~]���&��
                                 ÆqZ&�6%�L���ȿ
    [1] => �V�����Q@7)gL08�TA�#N��{�7�x�z[w����;
                                                                       X-�������Ј���I���v�3H�C��ꉓ�r�_�
)
```

If you want you can [contact me on a real-time communication platform](https://github.com/Benjamin-Loison/YouTube-operational-API#contact) for debugging that together.

**Comment by bsde1234** [comment]
Thanks for support, Now working.

**Comment by bsde1234** [comment]
Actually in loop it only works first time. Do I need to `unset` any thing?

**Comment by Benjamin-Loison** [comment]
> Actually in loop it only works first time. Do I need to `unset` any thing?

```php
<?php

    for($i = 0; $i < 2; $i++)
    {
        $cmd = "curl 'https://www.youtube.com/youtubei/v1/backstage/c...";
        exec($cmd, $output, $return_var);
        print_r($output);
        echo "Exit status: ".$return_var."<br>";
    }

?>
```

works fine on my end.

![Screenshot from 2022-12-22 03-56-16](https://user-images.githubusercontent.com/12752145/209045601-b258bf35-42c5-43f4-a815-0441024232f1.png)

**Comment by bsde1234** [comment]
[1] => {
    [2] =>   "error": {
    [3] =>     "code": 400,
    [4] =>     "message": "Invalid JSON payload received. Expected , or } after key:value pair.\nt last the rioters \"retreated\" . Find ou\n                    ^",
    [5] =>     "errors": [
    [6] =>       {
    [7] =>         "message": "Invalid JSON payload received. Expected , or } after key:value pair.\nt last the rioters \"retreated\" . Find ou\n                    ^",
    [8] =>         "domain": "global",
    [9] =>         "reason": "parseError"
    [10] =>       }
    [11] =>     ],
    [12] =>     "status": "INVALID_ARGUMENT"
    [13] =>   }
    [14] => }

**Comment by Benjamin-Loison** [comment]
Send the censored code generating this error, otherwise I can't help you.

**Comment by bahamas10** [comment]
just wanted to throw my own experience in here - this totally worked for me, thank you!  I was able to upload a scheduled post as well (which is great in case this method ever breaks in the future), the JSON body looked something like:


``` json
{
  "commentText": "who are you",
  "pollAttachment": {
    "choices": [
      "🤔",
      "🤗",
      "😴",
      "hi"
    ]
  },
  "scheduledPublishTimeSec": "1672599600"
}
```

Some notes:

- As noted by a user above, remove the `accept-encoding` header to get a JSON response back
- If you get a 400 error like i did for a while, make sure to remove any `content-length` header you are sending up if you modified the JSON yourself.  just omit it and `curl` will recalculate it for you.

**Comment by Benjamin-Loison** [comment]
@bahamas10 This seems to make sense, thank you for your insights.

**Comment by bsde1234** [comment]
> Send the censored code generating this error, otherwise I can't help you.

There was an error in the code. I didn't reset option in the loop. Now works. Thanks for the support.

**Comment by Armx-123** [comment]
Hi ! Is this method still working ?

**Comment by Benjamin-Loison** [comment]
@Armx-123 I confirm that [the method](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/102#issuecomment-1351790996) I mentioned still works.

**Comment by Armx-123** [comment]
While copying the Curl I see two options bash and cmd for which one should I go ?

**Comment by Armx-123** [comment]
@Benjamin-Loison Thanks I got it working on terminal using wsl. How can I do the same with python ?

**Comment by Benjamin-Loison** [comment]
@Armx-123 [curlconverter](https://github.com/curlconverter/curlconverter) [usually does the trick](https://codeberg.org/Benjamin_Loison/curlconverter/issues), otherwise you can execute the shell command from your Python code.

**Comment by Benjamin-Loison** [comment]
@Armx-123

What about curlconverter? It works fine in my case.

**Comment by Armx-123** [comment]
@Benjamin-Loison I tried out the website but the code executed with a `response 403` error

**Comment by Benjamin-Loison** [comment]
@Armx-123 What web-browser are you using?

**Comment by Armx-123** [comment]
> @Armx-123 [What web-browser are you using?](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/102#issuecomment-2243027245)

Brave Browser

**Comment by Benjamin-Loison** [comment]
Personal note:

I am unable to leverage [minimizeCURL.py](https://github.com/Benjamin-Loison/YouTube-operational-API/blob/79c1272879abca4561dff645c325320c31d8a6c8/tools/minimizeCURL.py), as there is a limit of posts that we too quickly exceed even on a fresh channel.

**Comment by Benjamin-Loison** [comment]
> I tried out the website but the code executed and the response returned a response 403 error

@Armx-123 May you share the complete JSON returned when you try with `curlconverter`?

**Comment by Armx-123** [comment]
@Benjamin-Loison Well, I got it working with a curl converter, but when I try to run the same program some time later, it gives a 403 Forbidden error no matter whether it's executed from WSL or Python code.

```{
  "error": {
    "code": 403,
    "message": "We weren't able to add your post. Please try again.",
    "errors": [
      {
        "message": "We weren't able to add your post. Please try again.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
```
And this was the same error I was getting earlier only in my Python code (not in wsl)

**Comment by Benjamin-Loison** [comment]
It seems that by default per account 6 posts can be posted afterwards we get:

```json
{
    "error": {
        "code": 429,
        "message": "CENSORED",
        "errors": [
            {
                "message": "CENSORED",
                "domain": "global",
                "reason": "rateLimitExceeded"
            }
        ],
        "status": "RESOURCE_EXHAUSTED"
    }
}
```

**Comment by Benjamin-Loison** [comment]
@Armx-123

Well it takes too much of my time but you can investigate the following which is mostly minimized and still work:

```python
import requests
import json
import blackboxprotobuf
import base64
import hashlib
import time

def getBase64Protobuf(message, typedef):
    data = blackboxprotobuf.encode_message(message, typedef)
    return base64.b64encode(data).decode('ascii')

SAPISID = 'CENSORED'
YOUR_CHANNEL_ID = 'UC...'

cookies = {
    'SID': 'CENSORED',
    '__Secure-1PSIDTS': 'sidts-CENSORED',
    '__Secure-1PSID': 'CENSORED',
    'APISID': 'CENSORED',
    'SAPISID': SAPISID,
}

currentTime = int(time.time())
SAPISIDHASH = f'{currentTime}_' + hashlib.sha1(f'{currentTime} {SAPISID} https://www.youtube.com'.encode('ascii')).digest().hex()

headers = {
    'X-Goog-Visitor-Id': 'CENSORED',
    'X-Goog-AuthUser': '7',
    'X-Origin': 'https://www.youtube.com',
    'Authorization': f'SAPISIDHASH {SAPISIDHASH}',
}

message = {
    '1': YOUR_CHANNEL_ID,
}

typedef = {
    '1': {
        'type': 'string'
    },
}

createBackstagePostParams = getBase64Protobuf(message, typedef)

json_data = {
    'context': {
        'client': {
            'clientName': 'WEB',
            'clientVersion': '2.20240722.00.00',
        },
    },
    'createBackstagePostParams': createBackstagePostParams,
    'commentText': 'My question',
    'pollAttachment': {
        'choices': [
            'My option 1',
            'My option 2',
        ],
    },
}

response = requests.post(
    'https://www.youtube.com/youtubei/v1/backstage/create_post',
    cookies=cookies,
    headers=headers,
    json=json_data,
)

print(json.dumps(response.json(), indent = 4))
text = response.text
print("We weren't able to add your post. Please try again." in text)
print('rateLimitExceeded' in text)
print('ENGAGEMENT_TYPE_POST_CREATE' in text)
```

Note that I am not keen with expiring requests.

**Comment by Armx-123** [comment]
@Benjamin-Loison Thanks a lot ! It's working for me now.
