### ISSUE TITLE
How to get timestamp with the most replayed graph values?

### ISSUE THREAD

**Issue by Shreyas-Dongre** [Benjamin-Loison/YouTube-operational-API#103]
Hey, I used your code to get normalized values of the most replayed graph. The result is just a array of `["heatMarkerIntensityScoreNormalized"]` values. Is there any way where in I can get the normalized value with its timestamp? Thanks

**Comment by Benjamin-Loison** [comment]
Maybe [this other issue](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/25) will interest you.

In fact each `heatMarkerIntensityScoreNormalized` is described not for a given timestamp but a period of time that is between `timeRangeStartMillis` and `timeRangeStartMillis + markerDurationMillis`. Note that `timeRangeStartMillis` and `markerDurationMillis` are just next to `heatMarkerIntensityScoreNormalized` in the JSON tree.

**Comment by Shreyas-Dongre** [comment]
Hi, I had overlooked the JSON tree, but yes I got it now! I could get timestamps easily using `timeRangeStartMillis`. Thankyou so much for your reply! Helped a lot!!

**Comment by Benjamin-Loison** [comment]
You're welcome, don't hesitate to reopen the issue if you have a similar problem.
