### ISSUE TITLE
Add `content-type: application/json; charset=utf-8` header

### ISSUE THREAD

**Issue by aynh** [Benjamin-Loison/YouTube-operational-API#129]
Could be a good addition on top of the API.

For example, Firefox will show response with JSON header like this:

[![2023-02-02-190102_1366x768_scrot](https://user-images.githubusercontent.com/99479536/216307529-739a90a6-0a47-4aac-8030-b31e3e2e97a1.png)](
https://vid.puffyan.us/api/v1/playlists/UUYzPXprvl5Y-Sf0g4vX-m6g)

Also some fetch wrapper like [ofetch](https://github.com/unjs/ofetch) will only parse the response as JSON if it has the JSON header as seen here:

https://github.com/unjs/ofetch/blob/f27660eae1c8bde65cad64670f15a891c804c3ea/src/utils.ts#L52-L54

With fallback to JSON if there is no content-type header at all

https://github.com/unjs/ofetch/blob/f27660eae1c8bde65cad64670f15a891c804c3ea/src/utils.ts#L45-L47

**Comment by Benjamin-Loison** [comment]
Thanks for the valuable input! :)
