### ISSUE TITLE
For search `type=channel` isn't working

### ISSUE THREAD

**Issue by napiyo** [Benjamin-Loison/YouTube-operational-API#144]
https://yt.lemnoslife.com/search?part=snippet&q=bbkivines&type=channel
above endpoint should return results only channels matching query, as google youtube api v3 does. but this returns videos instead of channels.

**Comment by Benjamin-Loison** [comment]
As precised in the *documentation*, https://github.com/Benjamin-Loison/YouTube-operational-API/blob/dda79e7b8f76ed128085c6b3c3da43a331e0f99b/index.php#L67

https://yt.lemnoslife.com/search only supports `type=video`, so it doesn't support `type=channels`.

Are you looking for https://yt.lemnoslife.com/noKey/search?part=snippet&q=bbkivines&type=channel? If not please precise why [YouTube Data API v3](https://developers.google.com/youtube/v3) [Search: list](https://developers.google.com/youtube/v3/docs/search/list) endpoint doesn't fit your needs.

**Comment by Benjamin-Loison** [comment]
Don't hesitate to re-open this issue by providing details as requested.
