### ISSUE TITLE
Music video ID's returns with " containsMusic: false " for Every song

### ISSUE THREAD

**Issue by ftk789** [Benjamin-Loison/YouTube-operational-API#15]
For an example  `https://yt.lemnoslife.com/videos?part=containsMusic&id=XXYlFuWEuKI` That ID is a song form The Weekend, It always returns with False even though it should be true? , Thanks in Advance

**Comment by Benjamin-Loison** [comment]
Don't hesitate to reopen the issue if you still are encountering your issue. As documented in the commit message, a recent YouTube UI update involved this issue.

[The Weekend](https://www.youtube.com/watch?v=XXYlFuWEuKI): https://yt.lemnoslife.com/videos?part=containsMusic&id=XXYlFuWEuKI (returning ` "containsMusic": true`)
[A not music video](https://www.youtube.com/watch?v=6ZRgVX8SYX4): https://yt.lemnoslife.com/videos?part=containsMusic&id=6ZRgVX8SYX4 (returning ` "containsMusic": false`)
