### ISSUE TITLE
Number of subscribers and videos not available for channels (`part=about`)

### ISSUE THREAD

**Issue by PaulElser** [Benjamin-Loison/YouTube-operational-API#151]
Hey,

I was wondering whether it would be possible to add the number of a channel's subscribers and videos to the `about` `part` for channels, since this is quite valuable information that is also displayed at the about tab of a channel's YouTube page.

So far I only found `subscriberCount` and `videoCount` for the `channels` endpoint, which unfortunately doesn't include the main channel.

Many thanks,
Paul

**Comment by Benjamin-Loison** [comment]
Hello, it seems that you are looking for https://yt.lemnoslife.com/noKey/channels?part=statistics&id=CHANNEL_ID. As mentioned in #91, providing data retrievable with YouTube Data API v3 has a lower prirority.
By the way I don't see the number of channel's videos on the `about` tab, am I missing it?
![image](https://user-images.githubusercontent.com/12752145/230040536-a6dcfacb-1c67-46ff-90b3-c7ee4b275159.png)

**Comment by PaulElser** [comment]
Thanks a lot for pointing me to the correct link! This was indeed what I was looking for. I wasn't aware of #91 and your focus on providing data that is not retrievable with YouTube Data API v3. 

The channel's subscribers and videos are not directly in the about tab but beneath the channel name in your screenshot. Since you are using `getJSONFromHTMLForcingLanguage("https://www.youtube.com/channel/$id/about");` I was assuming subscriberCount and videoCount could be retrievable aswell.

**Comment by Benjamin-Loison** [comment]
Indeed thanks for pointing me to this area of my screenshot.

**Comment by zakrian07** [comment]
@Benjamin-Loison can we get Videos tab all videos  as well if possible ?

**Comment by Benjamin-Loison** [comment]
@zakrian07 The following of this discussion as being unclear and not appropriate for this issue thread is on [Discord](https://discord.com/channels/933841502155706418/933841503103627316/1171430854808047686).
