### ISSUE TITLE
Community post API always returns null for `videoId` even if there should be one

### ISSUE THREAD

**Issue by tomernahum** [Benjamin-Loison/YouTube-operational-API#169]
For `/channels?part=community` and `/community` on the API, everything works fine, except `videoId` is always `null` even when a video is shared. The API returns data that looks like the community post is just text in this case.

I tested this by making a community post on my YouTube channel and clicking the video option, then selecting a video. Here is the post on YouTube: https://www.youtube.com/post/UgkxoDHL2ZHwXDRj5ONtgzZHpvYjff_IMLMX. The video shows up of course. However the API response for that id looks like this:       
There is no reference to the video and `videoId` is `null`, I'm pretty sure it should be the id of the shared video
```json
{
    "kind": "youtube#communityListResponse",
    "etag": "NotImplemented",
    "items": [
        {
            "kind": "youtube#community",
            "etag": "NotImplemented",
            "id": "UgkxoDHL2ZHwXDRj5ONtgzZHpvYjff_IMLMX",
            "snippet": {
                "id": "UgkxoDHL2ZHwXDRj5ONtgzZHpvYjff_IMLMX",
                "channelId": "UCFE4JpEblVGw9bxFy_aFHAg",
                "date": "27 minutes ago",
                "contentText": [
                    {
                        "text": "Testing"
                    }
                ],
                "likes": 0,
                "commentsCount": 0,
                "videoId": null,
                "images": [],
                "poll": null,
                "edited": false,
                "sharedPostId": null,
                "comments": {
                    "nextPageToken": "4qmFsgLxARIYVUNGRTRKcEVibFZHdzlieEZ5X2FGSEFnGtQBRWdsamIyMXRkVzVwZEhuS0FTZXlBU1JWWjJ0NGIwUklUREphU0hkWVJGSnFOVTlPZEdkNldraHdkbGxxWm1aZlNVMU1UVmpxQWdRUUFSZ0JxZ05iSWtjd0FOZ0JBZW9CSkZWbmEzaHZSRWhNTWxwSWQxaEVVbW8xVDA1MFozcGFTSEIyV1dwbVpsOUpUVXhOV1BJQkdGVkRSa1UwU25CRllteFdSM2M1WW5oR2VWOWhSa2hCWjBJUVkyOXRiV1Z1ZEhNdGMyVmpkR2x2YmclM0QlM0Q="
                }
            }
        }
    ]
}
```
Also I did a little ctrl-f-ing on that page's source and the `ytInitialData` variable has the video Id in 14 places so I don't know if that helps.

Thanks, I appreciate the API!

**Comment by Benjamin-Loison** [comment]
Thanks for the tests with [your community tab](https://www.youtube.com/@RemotHuman/community).

The problem is now solved, thank you for having reported it.

**Comment by tomernahum** [comment]
by the way is there any way to get the raw date of the community post? Right now it just returns a string like "1 day ago". Seems like that might be the only thing youtube exposes though

**Comment by Benjamin-Loison** [comment]
YouTube UI of https://www.youtube.com/@RemotHuman/community doesn't seem to bring us such raw date and:

```sh
curl -s 'https://www.youtube.com/@RemotHuman/community' > community.json
```

then you can navigate in `/contents/twoColumnBrowseResultsRenderer/tabs/3/tabRenderer/content/sectionListRenderer/contents/0/itemSectionRenderer/contents/0/` entries and try to find your raw date, but to the best of my knowledge there isn't anyone.
