### ISSUE TITLE
Channel primary `links` returned is empty

### ISSUE THREAD

**Issue by Paxsenix0** [Benjamin-Loison/YouTube-operational-API#198]
Hello! Sorry, if you not understand the title is, and my English is bad...

So last day I'm testing to this URL:

https://yt.lemnoslife.com/channels?part=about&handle=@mrbeast

But the response is giving `links` value empty

```json
{
    "kind": "youtube#channelListResponse",
    "etag": "NotImplemented",
    "items": [
        {
            "kind": "youtube#channel",
            "etag": "NotImplemented",
            "id": "UCX6OQ3DkcsbYNE6H8uQQuVA",
            "countryChannelId": "UCX6OQ3DkcsbYNE6H8uQQuVA",
            "about": {
                "stats": {
                    "joinedDate": 1329609600,
                    "viewCount": 31211999039,
                    "subscriberCount": 180000000
                },
                "description": "SUBSCRIBE FOR A COOKIE!",
                "title": "MrBeast",
                "details": {
                    "location": "United States"
                },
                "links": [],
                "handle": "@MrBeast"
            }
        }
    ]
}
```

**Comment by Benjamin-Loison** [comment]
I'll work on it before September 6.

**Comment by Benjamin-Loison** [comment]
Someone also has this issue on [Discord](https://discord.com/channels/933841502155706418/933841503103627316/1147113879369961522).

**Comment by Paxsenix0** [comment]
Thank you! but i still couldn't get icons of the links, do you have other solution for this? :)

**Comment by Benjamin-Loison** [comment]
I have [the feeling that thumbnails were removed](https://stackoverflow.com/posts/72650280/revisions) from the `About` section. Let me know if you are aware of any channel having link thumbnails.

**Comment by Paxsenix0** [comment]
Ohh okay, anyway thank you again!
