### ISSUE TITLE
How to get most popular shorts?

### ISSUE THREAD

**Issue by CodeCurosity** [Benjamin-Loison/YouTube-operational-API#199]
I want to fetch most popular shorts not by channel, I tried 

https://yt.lemnoslife.com/noKey/videos?part=short&chart=mostPopular

but it doesn't seem to work.

**Comment by Benjamin-Loison** [comment]
[YouTube Data API v3](https://developers.google.com/youtube/v3) (this is what you are using when reaching the no-key endpoint) [doesn't support shorts](https://developers.google.com/youtube/v3/docs/search/list).

Are you able to proceed to the search you are looking for with the YouTube UI? If so, how?

**Comment by CodeCurosity** [comment]
i removed noKey from endpoint, using your solution how come we can get
shorts from channel but now from public shorts without channel, i want to
get most popular shorts videos, how do i get them? thank you.

**Comment by Benjamin-Loison** [comment]
My code doesn't allow retrieving most popular short videos.
However, if you find a method to retrieve them on the YouTube UI, I can add a method to my API. Let me know if you know such a method.

**Comment by CodeCurosity** [comment]
How are you retrieving channels shorts? why it can't work for public shorts why it has to be specific for a channel?

**Comment by Benjamin-Loison** [comment]
My API is based on web scraping and I'm only aware of a method to retrieve channel shorts on YouTube UI.

**Comment by CodeCurosity** [comment]
OK, is it possible to get shorts from multiple channels at the same
endpoint or call?

**Comment by Benjamin-Loison** [comment]
As implementing such feature could lead to easy DDoS on the official instances, I won't add this feature, however you are free to host your own instance of my API and implement this feature.
