### ISSUE TITLE
Playlist extraction issue: returning the same `publishedAt` time for all videos

### ISSUE THREAD

**Issue by Jumman04** [Benjamin-Loison/YouTube-operational-API#201]
![image](https://github.com/Benjamin-Loison/YouTube-operational-API/assets/113237846/f17df322-3f6c-4027-a47a-2d1bef3ff8be)

While extracting playlist data I get this error that 'publishedAt' is returning the same time for all videos.

My link was: https://yt.lemnoslife.com/playlistItems?part=snippet&playlistId=PLizEqzsgQvPrPpVN1KXRHTw9GdHSKmFII

Above I have given a screenshot, showing that the first 3 videos are showing the same integer in terms of time.

Below I have loaded that playlist on YouTube, it appears that the published time of all the videos is not the same.

Playlist Link: https://www.youtube.com/playlist?list=PLizEqzsgQvPrPpVN1KXRHTw9GdHSKmFII

![image](https://github.com/Benjamin-Loison/YouTube-operational-API/assets/113237846/2322c0ed-58ce-4b7c-8fd2-833cf5c39de2)

**Comment by Benjamin-Loison** [comment]
Issue solved, thanks for reporting.
