### ISSUE TITLE
Can't retrieve any JSON response for `mostReplayed`

### ISSUE THREAD

**Issue by jun318** [Benjamin-Loison/YouTube-operational-API#208]
Thank you for developing this awesome tool.
I have been using this tool for several months and the tool perfectly worked. However, in these days, I cannot retrieve `mostReplayed`. I acknowledge that the latest revision (i.e., `380e6de`) is trying to fix this bug but still, some of the videos (e.g., video ID: `tauvb6bOrcU`) cannot be retrieved.

<img width="960" alt="image" src="https://github.com/Benjamin-Loison/YouTube-operational-API/assets/65419897/3b80b78b-a008-41b6-a1f2-73b7a80c4adc">
<img width="884" alt="image" src="https://github.com/Benjamin-Loison/YouTube-operational-API/assets/65419897/754f4f8f-6f42-4e8c-ad88-328bddad2906">

**Comment by Benjamin-Loison** [comment]
The video you provided just seem to not have any public most replayed data, am I wrong?
![image](https://github.com/Benjamin-Loison/YouTube-operational-API/assets/12752145/b63cbf65-6521-4093-96f0-258a97dc9105)

Contrarily to [this example](https://stackoverflow.com/q/72610552) for instance:

![image](https://github.com/Benjamin-Loison/YouTube-operational-API/assets/12752145/9bf1de65-3b02-426f-80b3-61757205b08c)

**Comment by Benjamin-Loison** [comment]
My bad I guess your issue is that it doesn't return any JSON response to your request, so I just solved this issue. Don't hesitate to re-open if it does not solve your problem.
