### ISSUE TITLE
Ability to pass your own API key

### ISSUE THREAD

**Issue by iamsharduld** [Benjamin-Loison/YouTube-operational-API#21]
Hi, 

Hope you are doing well! Ability to pass your own API key will greatly improve reliability and would give more control to the user

**Comment by Benjamin-Loison** [comment]
I don't get it, why not just using YouTube Data API v3 if it returns the data you are looking for and you have a YouTube Data API v3 developer key ?

**Comment by iamsharduld** [comment]
Thanks for your response! What I was trying to say is when calling the underlying API, eg. I want to get normalized heatMap for a given video, if I understand correctly the repo code uses 115 available keys and makes a hit to underlying video API. Instead of that, if we can have configuration to store the local key

**Comment by Benjamin-Loison** [comment]
I guess you come from https://stackoverflow.com/questions/72610552/most-replayed-data-of-youtube-video-via-api

My code contains two services:

1. The no-key service which relies on [YouTube Data API v3](https://developers.google.com/youtube/v3) [by using a file in /var/www/ytPrivate/keys.txt](https://github.com/Benjamin-Loison/YouTube-operational-API/blob/8743464335be23b1a0b7bf8aea802efbb3eb3c12/noKey/index.php#L6) full of such developer keys. This is the service you call when fetching https://yt.lemnoslife.com/noKey/videos?part=snippet&id=VIDEO_ID More information on https://yt.lemnoslife.com
2. The YouTube operational API endpoints relying on undocumented YouTube UI backend. For this [everybody has the same key](https://github.com/Benjamin-Loison/YouTube-operational-API/blob/8743464335be23b1a0b7bf8aea802efbb3eb3c12/common.php#L9) (which isn't a YouTube Data API v3 one) when reaching https://www.youtube.com However as mentioned in #11 as it isn't rate-limited with developer keys it is subject to unstability if used a lot. This is the service you reach when using https://yt.lemnoslife.com/videos?part=mostReplayed&id=VIDEO_ID

Now that things are clearer, you can check that you have the same YouTube UI backend key by inspecting `ytInitialData` JSON encoded JavaScript variable when reverse-engineering the YouTube UI webpage you are retrieving. So as far as I know avoid #11 issue (that is being detected as sending an unusual traffic according to Google servers) can't be bypassed as there isn't any other working key, just making the same request from another IP does the trick.

Let me know if you still have an interesting idea but as far as I have understood you weren't aware of it was working precisely behind the scene ^^.

**Comment by iamsharduld** [comment]
Got it, that makes it a lot clearer! Thanks for your quick response!

**Comment by Benjamin-Loison** [comment]
You're welcome, I may add something like this to the `README.md` if it seems required later on after having cleaned the code as described in #19.
