### ISSUE TITLE
This is shit 💩

### ISSUE THREAD

**Issue by nethriis** [Benjamin-Loison/YouTube-operational-API#214]

**Comment by nethriis** [comment]
You made ad for your repo everywhere

**Comment by nethriis** [comment]
💩💩💩💩

**Comment by Benjamin-Loison** [comment]
I just try to propose an alternative to the not existing features that people are looking for, if you are aware of alternatives to my repository, please let me know.

**Comment by Benjamin-Loison** [comment]
Since this ticket is not very constructive, I will close it and will let you the possibility of arguing more by reopening it.
