### ISSUE TITLE
Feature Request - Videos

### ISSUE THREAD

**Issue by zakrian07** [Benjamin-Loison/YouTube-operational-API#221]
Can you add a video param to parse channel videos?
I can see you are nicely pulling all info from the channel list if you add one more param  this feature can be added
> [Channels: list](https://developers.google.com/youtube/v3/docs/channels/list): https://yt.lemnoslife.com/channels?part=status,upcomingEvents,shorts,community,channels,about,approval,playlists,snippet,membership&cId=C_ID&id=CHANNEL_ID&handle=HANDLE&forUsername=USERNAME&order=viewCount(&pageToken=PAGE_TOKEN)

just add part as a video.

**Comment by Benjamin-Loison** [comment]
I do not understand your feature request. It seems you want the YouTube operational API to be able to parse https://www.youtube.com/channel/CHANNEL_ID/videos. [YouTube Data API v3 meets your needs](https://stackoverflow.com/a/74579030), no?

Related to #91.

**Comment by zakrian07** [comment]
im closing this and move the discussion to #91
