### ISSUE TITLE
Does 'about' part still work?

### ISSUE THREAD

**Issue by krasnoludkolo** [Benjamin-Loison/YouTube-operational-API#233]
Hello, I'm trying to use `about` part:

```
https://yt.lemnoslife.com/noKey/channels?part=about&id=UC2S75Ky4VF-MA8o8tpwTpkA
```

and I got
```json
{
  "error": {
    "code": 400,
    "message": "'about'",
    "errors": [
      {
        "message": "'about'",
        "domain": "youtube.part",
        "reason": "unknownPart",
        "location": "part",
        "locationType": "parameter"
      }
    ]
  }
}
```

Is this bug?

**Comment by Benjamin-Loison** [comment]
You are confusing no-key endpoint relying on [YouTube Data API v3](https://developers.google.com/youtube/v3) and web-scraping endpoints relying on my YouTube operational API, you are looking for https://yt.lemnoslife.com/channels?part=about&id=UC2S75Ky4VF-MA8o8tpwTpkA

Re-open this issue if it is still unclear to you.
