### ISSUE TITLE
Channels endpoint doesn't find "autogenerated" YouTube channels 

### ISSUE THREAD

**Issue by krasnoludkolo** [Benjamin-Loison/YouTube-operational-API#235]
Eg. channel:
https://www.youtube.com/channel/UC9r_nQL7uZ3eXQRFwzX7xZQ

(it's a channel from YouTube API point of view)

Calling this:
http://localhost:9001/channels?part=playlists,snippet&id=UC9r_nQL7uZ3eXQRFwzX7xZQ

I got an empty response (empty list).

**Comment by Benjamin-Loison** [comment]
What fields related to this example channel are you interested in?

Some fields are already retrievable with [YouTube Data API v3](https://developers.google.com/youtube/v3) [Channels: list](https://developers.google.com/youtube/v3/docs/channels/list) endpoint, as https://yt.lemnoslife.com/noKey/channels?part=snippet&id=UC9r_nQL7uZ3eXQRFwzX7xZQ shows.

**Comment by krasnoludkolo** [comment]
Okay, I was curious if there is something more there than in yt api.

**Comment by Benjamin-Loison** [comment]
If I remember correctly YouTube operational API is not compatible with *autogenerated* YouTube channels. However, I can add support for them, I just need someone to explain what is missing in YouTube Data API v3 that YouTube operational API can retrieve from YouTube UI.

**Comment by Benjamin-Loison** [comment]
You are right the `Popular Videos - HELLCARD` playlist with id `PLv0l5Jy32jh2sJRMlly0BInnhKu06VX__` from https://yt.lemnoslife.com/noKey/playlists?part=snippet&channelId=UC9r_nQL7uZ3eXQRFwzX7xZQ is not the expected one.
I am going to implement this feature.

**Comment by Benjamin-Loison** [comment]
@krasnoludkolo

[I added `channels?part=popular` endpoint](https://github.com/Benjamin-Loison/YouTube-operational-API/compare/2b4fc3304c2f34e02656dc60f3d2c5fc46aa144f...a1a9a7c3ea738153fc2400ec40ed4a742ef90885), as you requested.

**Comment by krasnoludkolo** [comment]
Hm, I updated my local instance and I got 
```
{
    "error": {
        "code": 400,
        "message": "Invalid part popular"
    }
}
```

after using 
```
http://localhost:9001/channels?part=popular&id=UC9r_nQL7uZ3eXQRFwzX7xZQ
```

How can I verify local version?

**Comment by Benjamin-Loison** [comment]
On http://localhost:9001 you should have

> This instance (my instance) uses version: a1a9a7c3ea738153fc2400ec40ed4a742ef90885

Do you confirm baving exactly this message?

**Comment by krasnoludkolo** [comment]
Ah, I didn't rebuild docker image. Now everything is fine, thanks for fast response!
