### ISSUE TITLE
Some YouTube channels have a URL which is not a `username`, `handle`, or `cId`

### ISSUE THREAD

**Issue by Draknek** [Benjamin-Loison/YouTube-operational-API#239]
Thanks for this project! I've found it very useful.

I am trying to get the channel ID from a set of user-provided URLs. Mostly they are in one of these forms:
`https://youtube.com/channel/[channel ID]`
`https://youtube.com/user/[username]`
`https://youtube.com/@[handle]`
`https://youtube.com/c/[custom URL]`

However, some of the URLs have this form, which I don't see how to convert into a channel ID:

`https://www.youtube.com/[custom URL]`

Here is an example of a problematic URL:

https://www.youtube.com/AphmauGaming

`AphmauGaming` does not resolve if queried as a username, handle, or cId. Did I miss the API that I need? If it doesn't exist, is it possible to add it?

Thanks for your time!

**Comment by Benjamin-Loison** [comment]
Channel type added thanks to `raw` filter.

https://yt.lemnoslife.com/channels?part=snippet&raw=AphmauGaming

now returns [`UCzYfz8uibvnB7Yc1LjePi4g`](https://www.youtube.com/channel/UCzYfz8uibvnB7Yc1LjePi4g).

Let me know if it does not fit your needs.

**Comment by Draknek** [comment]
Geez, way to make all the other open source maintainers look bad.

Works perfectly, thanks so much for the speedy fix!
