### ISSUE TITLE
This instance requires that you provide the appropriate `instanceKey` parameter!

### ISSUE THREAD

**Issue by isaac1620** [Benjamin-Loison/YouTube-operational-API#241]
How to you fix this one? Where can I get instanceKey?

**Comment by isaac1620** [comment]
This one https://yt0.lemnoslife.com/channels?part=shorts&id=UCK5y63TZxyNMEsDW4EWTEsg

**Comment by isaac1620** [comment]
Thank you @Benjamin-Loison 👏

**Comment by Benjamin-Loison** [comment]
It was never an officially supported instance, please use above one.

[On Discord](https://discord.com/channels/933841502155706418/933841503103627316/1208215061722828851) I described https://yt0.lemnoslife.com change with:

> As https://yt0.lemnoslife.com is on an almost free VPS and important to me VPS I set to private the associated YouTube operational API to reduce its workload otherwise I cannot even connect to it.

**Comment by isaac1620** [comment]
Damn, thanks for your contribution 🙏
