### ISSUE TITLE
The API seems to be down

### ISSUE THREAD

**Issue by catdogmat** [Benjamin-Loison/YouTube-operational-API#253]
Tried to visit the API's main page today and all I get is a Server Not Responding error. I've checked on multiple networks as well. Is this just me or is it down?

**Comment by catdogmat** [comment]
Closing as is back up!

**Comment by Benjamin-Loison** [comment]
Related to #165.

**Comment by catdogmat** [comment]
Opening as it's back down!

**Comment by catdogmat** [comment]
Back up, keeping this open as it happens alot

**Comment by Dmarcotrigiano** [comment]
I am not using this client, but I am witnessing outages/rate limits today and yesterday.

**Comment by Benjamin-Loison** [comment]
I hope to manage this issue tonight, if you are only interested in web-scraping based endpoints, then consider [hosting your own instance of the YouTube operational API](https://github.com/Benjamin-Loison/YouTube-operational-API/blob/5021d892f9c4752dfdd00bc1e106484f8bb864c3/README.md#install-your-own-instance-of-the-api).

**Comment by Benjamin-Loison** [comment]
I am starting working on this issue, sorry for the delay.

**Comment by Benjamin-Loison** [comment]
I added https://yt.lemnoslife.com webpage monitoring every minute, [here are the associated logs](https://yt0.lemnoslife.com/metrics/instances/yt/checkHomeLogs.txt), I should be notified if retrieving this webpage fails at some point.

**Comment by Benjamin-Loison** [comment]
I have been particularly notified tonight and [someone told me so as well on Discord](https://discord.com/channels/933841502155706418/933841503103627316/1223163095959076864) but I am currently busy so I will consider this issue again when it will happen again and hope that I will not be busy.
