### ISSUE TITLE
`nextPageToken` doesn't work after one time works.

### ISSUE THREAD

**Issue by quroom** [Benjamin-Loison/YouTube-operational-API#263]
When I test this code,

```py
import requests

channelId = 'UCLbOYoltlCD0LN06fSwKTsQ'

baseUrl = f'https://yt.lemnoslife.com/channels' # ?part=shorts&id={channelId}

nextPageToken = ''
index = 1
while True:
    params = {
        'part': 'shorts',
        'id': channelId,
    }
    if nextPageToken:
        params['pageToken'] = nextPageToken
    url = baseUrl
    #url = baseUrl + (f'&pageToken={nextPageToken}' if nextPageToken else '')
    #params = None
    response = requests.get(url, params = params).json()
    item = response['items'][0]
    print(f"page{index}.============================")
    for video in item['shorts']:
        print(video['title'])
    nextPageToken = item.get('nextPageToken')
    if not nextPageToken:
        break
    index+=1
```

It works well until page 2.
But I get this error after page 2.
What is the problem?

```json
{
    "error": {
        "code": 400,
        "message": "Invalid pageToken"
    }
}
```

**Comment by Benjamin-Loison** [comment]
Personal notes:

```bash
URL='http://localhost/YouTube-operational-API/channels?part=shorts&id=UCLbOYoltlCD0LN06fSwKTsQ' && DATA=`curl -s "$URL"` && echo $DATA | jq .items[0].shorts[].videoId | wc -l && NEXT_PAGE_TOKEN=`echo $DATA | jq -r .items[0].nextPageToken` && curl "$URL&pageToken=$NEXT_PAGE_TOKEN"
```

```py
import requests

CHANNEL_ID = 'UCLbOYoltlCD0LN06fSwKTsQ'

URL = f'http://localhost/YouTube-operational-API/channels'

params = {
    'part': 'shorts',
    'id': CHANNEL_ID,
}
    
index = 1
videoIds = set()

while True:
    item = requests.get(URL, params = params).json()['items'][0]
    print(f"page {index}")
    for video in item['shorts']:
        videoIds.add(video['videoId'])
    print(len(videoIds))
    nextPageToken = item.get('nextPageToken')
    if not nextPageToken:
        break
    index += 1
    params['pageToken'] = nextPageToken
    #print(nextPageToken)
```

**Comment by quroom** [comment]
> Thank you for reporting.
> 
> Related to #264.
> 
> Personal notes:
> 
> ```bash
> URL='http://localhost/YouTube-operational-API/channels?part=shorts&id=UCLbOYoltlCD0LN06fSwKTsQ' && DATA=`curl -s "$URL"` && echo $DATA | jq .items[0].shorts[].videoId | wc -l && NEXT_PAGE_TOKEN=`echo $DATA | jq -r .items[0].nextPageToken` && curl "$URL&pageToken=$NEXT_PAGE_TOKEN"
> ```
> 
> ```py
> import requests
> 
> CHANNEL_ID = 'UCLbOYoltlCD0LN06fSwKTsQ'
> 
> URL = f'http://localhost/YouTube-operational-API/channels'
> 
> params = {
>     'part': 'shorts',
>     'id': CHANNEL_ID,
> }
>     
> index = 1
> videoIds = set()
> 
> while True:
>     item = requests.get(URL, params = params).json()['items'][0]
>     print(f"page {index}")
>     for video in item['shorts']:
>         videoIds.add(video['videoId'])
>     print(len(videoIds))
>     nextPageToken = item.get('nextPageToken')
>     if not nextPageToken:
>         break
>     index += 1
>     params['pageToken'] = nextPageToken
>     #print(nextPageToken)
> ```

Does this code works only in local host? Or does this code has issue?

**Comment by Benjamin-Loison** [comment]
It works both on localhost and with the official YouTube operational API instance. See [YouTube-operational-API/wiki/Glossary/0be0be6df7142cd10f8c0ce1504b1c0a82dbb416](https://github.com/Benjamin-Loison/YouTube-operational-API/wiki/Glossary/0be0be6df7142cd10f8c0ce1504b1c0a82dbb416) for more details. 

If you want it to use the official YouTube operational API instance, then change:

```diff
5c5
< URL = f'http://localhost/YouTube-operational-API/channels'
---
> URL = f'https://yt.lemnoslife.com/channels'
```

**Comment by quroom** [comment]
> It works both on localhost and with the official YouTube operational API instance. See [YouTube-operational-API/wiki/Glossary/0be0be6df7142cd10f8c0ce1504b1c0a82dbb416](https://github.com/Benjamin-Loison/YouTube-operational-API/wiki/Glossary/0be0be6df7142cd10f8c0ce1504b1c0a82dbb416) for more details.
> 
> If you want it to use the official YouTube operational API instance, then change:
> 
> ```diff
> 5c5
> < URL = f'http://localhost/YouTube-operational-API/channels'
> ---
> > URL = f'https://yt.lemnoslife.com/channels'
> ```

It's weird situation.
Same code didn't work yesterday.
Now it works very well.

**Comment by Benjamin-Loison** [comment]
> [Benjamin-Loison](https://github.com/Benjamin-Loison) closed this as [completed](https://github.com/Benjamin-Loison/YouTube-operational-API/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in [4c01f0d](https://github.com/Benjamin-Loison/YouTube-operational-API/commit/4c01f0da14b4dc7d74f5167b870efaa638981c8f) [13 hours ago](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/263#event-12419981069)

Source: [above](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/263#event-12419981069)

You are relying on https://yt.lemnoslife.com website which I modified the source code according to above commit to solve the issue you reported.

**Comment by quroom** [comment]
@Benjamin-Loison Now I understand what you are saying. 
Thanks for quick response.
