### ISSUE TITLE
"Fetching chapters" can't work any more

### ISSUE THREAD

**Issue by stariver1862** [Benjamin-Loison/YouTube-operational-API#298]
It worked before.
e.g.: https://yt.lemnoslife.com/videos?part=chapters&id=IkXH9H2ofa0
Very strange

**Comment by Benjamin-Loison** [comment]
Issue solved, thanks for reporting.

**Comment by stariver1862** [comment]
Great!  Thanks for creating and setting up this service!  I'm able to run some interesting personal projects.
