### ISSUE TITLE
The `search` for Korean `short`s is no more working!

### ISSUE THREAD

**Issue by KimHyeonGyeom** [Benjamin-Loison/YouTube-operational-API#300]
Hello, I have been using your API in South Korea. Until a few weeks ago, I was able to search and retrieve shorts of Korean works without any issues, but at some point, the results started coming back as `null`. Could you please take a look when you have a chance?

url : https://yt.lemnoslife.com/search?part=id,snippet&q=%EA%B5%BF%ED%8C%8C%ED%8A%B8%EB%84%88&type=short

![image](https://github.com/user-attachments/assets/57c442f7-ad6a-4310-ba18-1a36e018d344)

**Comment by Benjamin-Loison** [comment]
[As someone figured out on Discord](https://discord.com/channels/933841502155706418/933841503103627316/1282891828277805138), it does not work for English searches as well. I am investigating the issue.

**Comment by Benjamin-Loison** [comment]
The solution to this issue is not very complicated but requires a *significant*, in my opinion, API change by introducing a new Protobuf dependency.

@KimHyeonGyeom do you host your own instance of the YouTube operational API or rely on the official instance one at https://yt.lemnoslife.com? [The same question applies to the person on Discord]() who can either answer here or on Discord. Your answer will help me to figure out how to proceed to this *significant* change.

**Comment by KimHyeonGyeom** [comment]
I’m sorry for the delayed response. I am relying solely on the instance of https://yt.lemnoslife.com!

**Comment by KimHyeonGyeom** [comment]
@Benjamin-Loison Sorry, is this going to take longer to resolve?

**Comment by Benjamin-Loison** [comment]
I am still working on #303 but it should not take me more than today, hence I will work on your issue today.

**Comment by Benjamin-Loison** [comment]
#265 solved.

**Comment by Benjamin-Loison** [comment]
@KimHyeonGyeom Are the first 10 results fine for you or you need more?

**Comment by Benjamin-Loison** [comment]
Personal notes:

<details>
<summary>Diff showing debugging:</summary>

```diff
diff --git a/search.php b/search.php
index 25210bd..4fa189f 100644
--- a/search.php
+++ b/search.php
@@ -13,6 +13,16 @@
 
 include_once 'common.php';
 
+includeOnceProtos([
+    'BrowseShorts',
+    'Sub0BrowseShorts',
+    'Sub1BrowseShorts',
+    'Sub2BrowseShorts',
+    'Sub3BrowseShorts',
+    'Sub4_7BrowseShorts',
+    'Sub4_9BrowseShorts',
+]);
+
 $realOptions = [
     'id',
     'snippet',
@@ -112,14 +122,58 @@ function getAPI($id, $order, $continuationToken)
                     'clientVersion' => MUSIC_VERSION
                 ]
             ],
-            'query' => str_replace('"', '\"', $_GET['q'])
         ];
+        if(isset($_GET['type']) && $_GET['type'] === 'short') {
+            /*
+            $browseShorts = (new \Sub3BrowseShorts())
+                                ->setSeven((new \Sub4_7BrowseShorts())
+                                    ->setTwelve(26));
+            $continuation = base64_encode($browseShorts->serializeToString());
+            die("!$continuation!"); // matches Python
+            $browseShorts = ((new \Sub4_7BrowseShorts())
+                                    ->setTwelve(26));
+            $continuation = base64_encode($browseShorts->serializeToString());
+            die("!$continuation!"); // matches Python
+            $browseShorts = (new \Sub3BrowseShorts())->setNine(new \Sub4_9BrowseShorts());
+            $continuation = base64_encode($browseShorts->serializeToString());
+            die("!$continuation!"); // matches Python
+            $browseShorts = new \Sub4_9BrowseShorts();
+            $continuation = base64_encode($browseShorts->serializeToString());
+            die("!$continuation!");*/
+            // three differs with Python
+            $sub1BrowseShorts = (new \Sub1BrowseShorts())
+                        ->setTwo((new \Sub2BrowseShorts())
+                            ->setEighteen((new \Sub3BrowseShorts())
+                                ->setSeven((new \Sub4_7BrowseShorts())
+                                    ->setTwelve(26))
+                                ->setNine(new \Sub4_9BrowseShorts())));
+            /*$continuation = base64_encode($browseShorts->serializeToString());
+            die($continuation);*/ // matches Python
+            /*$browseShorts = (new \Sub0BrowseShorts())
+                    ->setThree(base64_encode($sub1BrowseShorts->serializeToString()));
+            $continuation = base64_encode($browseShorts->serializeToString());
+            die($continuation);*/
+            // The following does not only return shorts no matter if comment `setNine`
+            $browseShorts = (new \BrowseShorts())
+                ->setTwo((new \Sub0BrowseShorts())
+                    ->setTwo('test')
+                    ->setThree(base64_encode($sub1BrowseShorts->serializeToString()))
+                    ->setEighteen(1))
+                ->setThree(52047873)
+                ->setFour('search-page');
+
+            $continuation = base64_encode($browseShorts->serializeToString());
+            //die($continuation);
+            $rawData['continuation'] = $continuation;
+        } else {
+            $rawData['query'] = str_replace('"', '\"', $_GET['q']);
+            if($typeBase64 !== '') {
+                $rawData['params'] = $typeBase64;
+            }
+        }
         if($continuationTokenProvided) {
             $rawData['continuation'] = $continuationToken;
         }
-        if($typeBase64 !== '') {
-            $rawData['params'] = $typeBase64;
-        }
         $opts = [
                'http' => [
                    'method' => 'POST',
@@ -127,7 +181,9 @@ function getAPI($id, $order, $continuationToken)
                    'content' => json_encode($rawData),
                ]
         ];
+        //$json = getJSON('http://localhost/https://www.youtube.com/youtubei/v1/search?key=' . UI_KEY, $opts);
         $json = getJSON('https://www.youtube.com/youtubei/v1/search?key=' . UI_KEY, $opts);
+        die(json_encode($json));
         if(isset($_GET['type']) && $_GET['type'] === 'short')
         {
             $contents = $json['contents']['twoColumnSearchResultsRenderer']['primaryContents']['sectionListRenderer']['contents'][0]['itemSectionRenderer']['contents'];
```
</details>

**Comment by KimHyeonGyeom** [comment]
> @KimHyeonGyeom처음 20개 결과가 괜찮은가요, 아니면 더 필요한가요?
> 
> 개인적인 메모:
> 
> PHP의 JSON과 YouTube UI에서 모두 검색된 개수입니다.

20 is plenty!

**Comment by Benjamin-Loison** [comment]
Personal notes:

When just pass *굿파트너* to `q`, it does not seem to return shorts.

**Comment by Benjamin-Loison** [comment]
Fix deployed, let me know if you have issues.

Thanks for have reported this issue.

**Comment by Benjamin-Loison** [comment]
Personal notes:

Next time have to face such Protobuf will ask on Discord if some people know how to better proceed. Don't forget to provide a minimal reproducible example and a wanted example code.

**Comment by KimHyeonGyeom** [comment]
@Benjamin-Loison Can't you use it locally? I'm using docker with the main branch and have the same problem as before.

**Comment by Benjamin-Loison** [comment]
@KimHyeonGyeom 

- https://yt.lemnoslife.com/search?part=id,snippet&q=%EA%B5%BF%ED%8C%8C%ED%8A%B8%EB%84%88&type=short
- http://localhost/YouTube-operational-API/search?part=snippet&q=%EA%B5%BF%ED%8C%8C%ED%8A%B8%EB%84%88&type=short

work fine.

I believe that your Docker container/image (I forgot how all that work) is not up-to-date.

**Comment by Benjamin-Loison** [comment]
Note that the homepage of the YouTube operational API instance shows the commit used:

> This instance (yt5.lemnoslife.com) uses version: [fa0b1f6a9c713793490830a159820a9241a19ae6](https://github.com/Benjamin-Loison/YouTube-operational-API/commit/fa0b1f6a9c713793490830a159820a9241a19ae6)

Source: https://yt.lemnoslife.com

**Comment by KimHyeonGyeom** [comment]
“When running locally with Docker, the search request returns a 500 error, and calling videos? shows a warning like in the image. Is there an additional configuration I need to set up?”


![image](https://github.com/user-attachments/assets/cbe78bb7-5a86-4576-a96e-257bb2d1fee6)
[19/Sep/2024:01:45:15 +0000] "GET /search?part=snippet&q=%EA%B5%BF%ED%8C%8C%ED%8A%B8%EB%84%88&type=short HTTP/1.1" 500 218 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"


![image](https://github.com/user-attachments/assets/a543bc97-db7d-452f-95d7-ada74dc9cb22)
![image](https://github.com/user-attachments/assets/6e9d1a48-271e-4a4f-81d2-46480c619272)

**Comment by Benjamin-Loison** [comment]
@KimHyeonGyeom Is there an error in logs when fetching `/search?part=snippet&q=%EA%B5%BF%ED%8C%8C%ED%8A%B8%EB%84%88&type=short`?

**Comment by KimHyeonGyeom** [comment]
> @KimHyeonGyeom가져올 때 로그에 오류가 있나요 `/search?part=snippet&q=%EA%B5%BF%ED%8C%8C%ED%8A%B8%EB%84%88&type=short`?

“Yes, when I send the API request, it returns a 500 response.”

response : [2024년 9월 19일:01:45:15 +0000] "GET /search?part=snippet&q=%EA%B5%BF%ED%8C%8C%ED%8A%B8%EB%84%88&type=short HTTP/1.1" 500 218 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"

**Comment by Benjamin-Loison** [comment]
What you sent me are *access* logs (`/var/log/apache2/access.log` on my Linux Mint 22 Cinnamon) I am asking for *error* logs (`/var/log/apache2/error.log` on my Linux Mint 22 Cinnamon).

What commit is shown on your instance homepage, as I mentioned in [#issuecomment-2359738845](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/300#issuecomment-2359738845)?

**Comment by Benjamin-Loison** [comment]
About [#issuecomment-2359809058](#issuecomment-2359809058), concerning warnings you can get rid of tests like:

https://github.com/Benjamin-Loison/YouTube-operational-API/blob/0ddadb17ef58624da1b87cf0eee9592db4a5055d/videos.php#L5-L34

**Comment by KimHyeonGyeom** [comment]
I’m sorry, I didn’t understand what I need to check.

**Comment by Benjamin-Loison** [comment]
Send here the result of `curl http://localhost:8081`.

**Comment by Benjamin-Loison** [comment]
Ok so your instance is up to date. How have you installed your Docker YouTube operational API instance, have you followed the official guide [blob/0ddadb17ef58624da1b87cf0eee9592db4a5055d/README.md#run-the-api-with-docker](https://github.com/Benjamin-Loison/YouTube-operational-API/blob/0ddadb17ef58624da1b87cf0eee9592db4a5055d/README.md#run-the-api-with-docker)?

**Comment by KimHyeonGyeom** [comment]
Yes, I followed the official guide exactly.

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Personal notes:</summary>

On my Linux Mint 22 Cinnamon Framework 13:

```bash
docker container ls
```
```
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

```bash
docker image ls
```
```
REPOSITORY                      TAG       IMAGE ID       CREATED         SIZE
...
php                             8.2-cli   36ed67830a2e   9 months ago    529MB
...
```
</details>

**Comment by Benjamin-Loison** [comment]
@KimHyeonGyeom On what OS are you?

**Comment by KimHyeonGyeom** [comment]
I’m using Ubuntu.

**Comment by Benjamin-Loison** [comment]
The issue is that Protobuf is not yet compliant with YouTube operational API, I will investigate that after 12:00 UTC+2

Related to #265.

**Comment by Benjamin-Loison** [comment]
Let me know if with the new commit you still have the issue.

**Comment by KimHyeonGyeom** [comment]
Everything is working fine now! Thank you!
