### ISSUE TITLE
`channels?part=shorts` endpoint broken

### ISSUE THREAD

**Issue by jasongrishkoff** [Benjamin-Loison/YouTube-operational-API#304]
For example: https://yt.lemnoslife.com/channels?part=shorts&id=UCWZp4y1jqBuvLtiyxSs_ZBw

Many of the fields are null:
```json
{
    "videoId": null,
    "title": null,
    "thumbnails": null,
    "viewCount": 0,
    "frame0Thumbnails": null,
    "channelId": "UCWZp4y1jqBuvLtiyxSs_ZBw"
}
```

Seems to have broken recently?

**Comment by Benjamin-Loison** [comment]
Maybe related to #300.

**Comment by Benjamin-Loison** [comment]
Fix deployed, thanks for reporting.

Related to #24.
