### ISSUE TITLE
YouTube scrapping

### ISSUE THREAD

**Issue by tekinc** [Benjamin-Loison/YouTube-operational-API#320]
Hi, great job with this API. I was in the middle of importing millions of videos but it didn't complete now that you have suspended your service. 

What would you recommend the best way to accomplish this?

**Comment by Benjamin-Loison** [comment]
What do you mean by *importing millions of videos*?

Related to #317.

**Comment by tekinc** [comment]
Import millions of video records.

**Comment by Benjamin-Loison** [comment]
Without further details as requested (*records* not helping), I close this issue.

See https://yt.lemnoslife.com for alternatives.

**Comment by tekinc** [comment]
Hi, how can I order by date using youtube v1 api?

**Comment by Benjamin-Loison** [comment]
You mean YouTube Data API v3 or YouTube operational API? See [YouTube-operational-API/wiki/Glossary/a6950ce5b5b5809b41129a0d1ded16b039a64358](https://github.com/Benjamin-Loison/YouTube-operational-API/wiki/Glossary/a6950ce5b5b5809b41129a0d1ded16b039a64358) if unsure.

**Comment by Benjamin-Loison** [comment]
What are you searching? Videos, shorts channels?

**Comment by tekinc** [comment]
I am using YouTube operational API and am searching for videos.

**Comment by Benjamin-Loison** [comment]
Let me know if [Webscrap_any_website/src/commit/12586241ddbb0651f639565cd0bf65085fa42d16/https:/www.youtube.com/results/main.py#](https://codeberg.org/Benjamin_Loison/Webscrap_any_website/src/commit/12586241ddbb0651f639565cd0bf65085fa42d16/https:/www.youtube.com/results/main.py){[L112](https://codeberg.org/Benjamin_Loison/Webscrap_any_website/src/commit/12586241ddbb0651f639565cd0bf65085fa42d16/https:/www.youtube.com/results/main.py#L112),[L14-L18](https://codeberg.org/Benjamin_Loison/Webscrap_any_website/src/commit/12586241ddbb0651f639565cd0bf65085fa42d16/https:/www.youtube.com/results/main.py#L14-L18)} do not meet your needs.

**Comment by tekinc** [comment]
Thanks but I am using your php implimentation. Do you have the fix for that?

**Comment by Benjamin-Loison** [comment]
I do not plan to add PHP support for this feature, let me know if I should add an HTTP interface, see [Webscrap_any_website/src/commit/12586241ddbb0651f639565cd0bf65085fa42d16/README.md#install-your-own-http-interface-instance](https://codeberg.org/Benjamin_Loison/Webscrap_any_website/src/commit/12586241ddbb0651f639565cd0bf65085fa42d16/README.md#install-your-own-http-interface-instance), that you would have to host for this feature.

**Comment by tekinc** [comment]
It would be great if you could add it to http interface. I am already hosting your youtube operational api.

**Comment by Benjamin-Loison** [comment]
Note that the solution I proposed you, see [#issuecomment-2445499106](#issuecomment-2445499106), is independent from YouTube operational API.

[I just updated the HTTP interface](https://codeberg.org/Benjamin_Loison/Webscrap_any_website/commit/b3c42ec68b56061434f8b32620f67783e35242c8) as you requested, such that:

```bash
curl -X GET 'http://localhost:8080/https:/www.youtube.com/results?search_query=Minecraft' -d 'type=video' -d 'sort by=upload date'
```

should meet your needs.

**Comment by tekinc** [comment]
Great, thanks

**Comment by tekinc** [comment]
Hi, sorry is it possible for you to add this to the Youtube operational api? I have already the entire flow in place and would to keep it.

**Comment by Benjamin-Loison** [comment]
Sorry but I won't add this feature to the YouTube operational API, see [##issuecomment-2450624202](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/327#issuecomment-2450624202) for details about why.

**Comment by tekinc** [comment]
Understood, is it possible to guide me where I can make that change? All i need is to set the order param correctly.

**Comment by Benjamin-Loison** [comment]
If you mean helping me to tell you what to change in YouTube operational API, then forget it. I have not yet done such *complex* thing and I do not recommend anyone to do so. Generating Protobuf in PHP is a hell while in Python it is very easy.

**Comment by tekinc** [comment]
Didn't realize is was that complicataeed in Youtube operational API. You already have a viewCount order parameter, I thought it would be easy to add "age" or "date". I guess not?

![image](https://github.com/user-attachments/assets/22f8d2f9-38d1-47c4-b4db-9aff4ca34afc)

**Comment by Benjamin-Loison** [comment]
The code you selected is a hardcoded Protobuf string, for your very precise use case (`search?q=QUERY&type=video&order=uploadDate`) another one might fit your needs. However, it acts as an unoptimized blackbox which is very easily no more interesting, for instance such a hardcoded approach would not work for `search?q=QUERY&type=channel&order=uploadDate`, as `type=channel` and `order=uploadDate` would need to merge 2 hardcoded blackbox Protobufs with such an approach, so you would have to hardcoded the merge result and so on. Hence, the number of hardcoded Protobuf string would be exponential... So it is not an approach that I recommend, as it results in Protobuf hell syntax as we can see at the bottom of your screen. The purpose of my work is to meet all needs, not just your precise use case at the expense of the needs of others, that's why I focus for this kind of *complex* feature on Webscrap any website as it is far better implemented and such better implementation is not easily possible in PHP as far as I know.
Please do not ask me further assistance on what I consider as a bad approach.

**Comment by tekinc** [comment]
Thanks for the response. Last question, I am only using the Youtube operational api for type=video searches. How could I generate a protobuf string to replace that hardcoded one to support these parameters "q=QUERY&type=video&order=uploadDate" ?
