### ISSUE TITLE
Most replayed data returns `null` for some videos having such data

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/YouTube-operational-API#40]
While a video such as [`-1I5u6jLZ9U`](https://www.youtube.com/watch?v=-1I5u6jLZ9U) has some most replayed data, YouTube operational API Videos: list endpoint returns `null` for the `mostReplayed` field.

[`wCQfkEkePx8`](https://www.youtube.com/watch?v=wCQfkEkePx8) doesn't have this issue for instance.

**Comment by amastis** [comment]
In https://github.com/Benjamin-Loison/YouTube-operational-API/blob/1ee4f05d3e952d830a498fb9c9d94aac63e7c568/videos.php#L168 

you assume that the heatmap will be the first item, but it is not the case when there are chapters. The 'markersMap' array may have more elements in it, therefore you should check whether there are more elements in the array and then check the elements of the array to contain "key": "HEATSEEKER" for the mostReplayed data values, before you do the rest of your key lookups.

The screenshot below is from the video id that you have mentioned.

<img width="660" alt="Screen Shot 2022-10-04 at 3 26 26 AM" src="https://user-images.githubusercontent.com/37512516/193761716-768e6df3-b370-4919-9732-465546e3571c.png">

**Comment by Benjamin-Loison** [comment]
@amastis
Thank you for your initial bug report and your insight!
